manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: r2d2rogers
      url-base: https://github.com/r2d2rogers
    - name: DiogoDoreto
      url-base: https://github.com/DiogoDoreto
  projects:
    - name: zmk
      #remote: DiogoDoreto
      remote: r2d2rogers
      #revision: waterfowl-encoders
      revision: main
      import: app/west.yml
  self:
    path: config
