manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: r2d2rogers
      url-base: https://github.com/r2d2rogers
    - name: DiogoDoreto
      url-base: https://github.com/DiogoDoreto
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: r2d2rogers
      revision: main
      import: app/west.yml
    - name: zmk
      remote: petejohanson
      revision: stephen/split-encoder
        # remote: DiogoDoreto
        # revision: waterfowl-encoders
      import: app/west.yml
  self:
    path: config
